apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: >-
      [
      {
        "apiVersion": "kfdef.apps.kubeflow.org/v1",
        "kind": "KfDef",
        "metadata": {
            "name": "kubeflow",
            "namespace": "kubeflow"
        },
        "spec": {
            "applications": [
              {
                  "kustomizeConfig": {
                    "repoRef": {
                        "name": "manifests",
                        "path": "stacks/ibm/application/istio-stack"
                    }
                  },
                  "name": "istio-stack"
              },
              {
                  "kustomizeConfig": {
                    "repoRef": {
                        "name": "manifests",
                        "path": "stacks/ibm/application/cluster-local-gateway"
                    }
                  },
                  "name": "cluster-local-gateway"
              },
              {
                  "kustomizeConfig": {
                    "repoRef": {
                        "name": "manifests",
                        "path": "stacks/ibm/application/istio"
                    }
                  },
                  "name": "istio"
              },
              {
                  "kustomizeConfig": {
                    "repoRef": {
                        "name": "manifests",
                        "path": "stacks/ibm/application/add-anonymous-user-filter"
                    }
                  },
                  "name": "add-anonymous-user-filter"
              },
              {
                  "kustomizeConfig": {
                    "repoRef": {
                        "name": "manifests",
                        "path": "application/v3"
                    }
                  },
                  "name": "application"
              },
              {
                  "kustomizeConfig": {
                    "repoRef": {
                        "name": "manifests",
                        "path": "stacks/ibm/application/bootstrap"
                    }
                  },
                  "name": "bootstrap"
              },
              {
                  "kustomizeConfig": {
                    "repoRef": {
                        "name": "manifests",
                        "path": "stacks/ibm/application/cert-manager-crds"
                    }
                  },
                  "name": "cert-manager-crds"
              },
              {
                  "kustomizeConfig": {
                    "repoRef": {
                        "name": "manifests",
                        "path": "stacks/ibm/application/cert-manager-kube-system-resources"
                    }
                  },
                  "name": "cert-manager-kube-system-resources"
              },
              {
                  "kustomizeConfig": {
                    "repoRef": {
                        "name": "manifests",
                        "path": "stacks/ibm/application/cert-manager"
                    }
                  },
                  "name": "cert-manager"
              },
              {
                  "kustomizeConfig": {
                    "repoRef": {
                        "name": "manifests",
                        "path": "stacks/ibm"
                    }
                  },
                  "name": "kubeflow-apps"
              },
              {
                  "kustomizeConfig": {
                    "repoRef": {
                        "name": "manifests",
                        "path": "metacontroller/base"
                    }
                  },
                  "name": "metacontroller"
              },
              {
                  "kustomizeConfig": {
                    "repoRef": {
                        "name": "manifests",
                        "path": "stacks/ibm/application/metadata"
                    }
                  },
                  "name": "metadata"
              },
              {
                  "kustomizeConfig": {
                    "repoRef": {
                        "name": "manifests",
                        "path": "stacks/ibm/application/spark-operator"
                    }
                  },
                  "name": "spark-operator"
              },
              {
                  "kustomizeConfig": {
                    "repoRef": {
                        "name": "manifests",
                        "path": "knative/installs/generic"
                    }
                  },
                  "name": "knative"
              },
              {
                  "kustomizeConfig": {
                    "repoRef": {
                        "name": "manifests",
                        "path": "kfserving/installs/generic"
                    }
                  },
                  "name": "kfserving"
              },
              {
                  "kustomizeConfig": {
                    "repoRef": {
                        "name": "manifests",
                        "path": "stacks/ibm/application/spartakus"
                    }
                  },
                  "name": "spartakus"
              },
              {
                  "kustomizeConfig": {
                    "repoRef": {
                        "name": "manifests",
                        "path": "stacks/ibm/application/tensorboard"
                    }
                  },
                  "name": "tensorboard"
              },
              {
                "kustomizeConfig": {
                  "repoRef": {
                      "name": "manifests",
                      "path": "stacks/ibm/application/openaihub"
                  }
                },
                "name": "openaihub"
              }
            ],
            "repos": [
              {
                  "name": "manifests",
                  "uri": "https://github.com/moficodes/manifests/archive/v1.1.0.tar.gz"
              }
            ],
            "version": "v1.1.0"
        }
      }
      ]
    capabilities: Basic Install
    categories: "AI/Machine Learning"
    description: "OpenAIHub Operator for deployment and management of OpenAIHub on Kubeflow"
    support: Kubeflow
    repository: https://github.com/openaihub/openaihub-operator
    createdAt: '2020-10-13T00:00:00Z'
    containerImage: aipipeline/openaihub-operator:v1.1.0
    certified: 'False'
  name: openaihub.v1.1.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: KfDef is the Schema for the applications API
      kind: KfDef
      name: kfdefs.kfdef.apps.kubeflow.org
      version: v1
      displayName: OpenAIHub
      group: kfdef.apps.kubeflow.org
  description: "OpenAIHUb Operator for deployment and management of Kubeflow components. Applicable for Kubeflow versions 1.0 and above. Check [Kubeflow Operator documentation](https://github.com/kubeflow/kfctl/blob/master/operator.md) for more details."
  displayName: OpenAIHub
  icon: 
  - base64data: iVBORw0KGgoAAAANSUhEUgAAAFwAAABcCAYAAADj79JYAAABSGlDQ1BJQ0MgUHJvZmlsZQAAKJFjYGASSSwoyGFhYGDIzSspCnJ3UoiIjFJgf8LAxcDLIMwgxqCZmFxc4BgQ4ANUwgCjUcG3awyMIPqyLsisG2fuuTIYN71LbZKr3P7jdAKmehTAlZJanAyk/wBxenJBUQkDA2MKkK1cXlIAYncA2SJFQEcB2XNA7HQIewOInQRhHwGrCQlyBrJvANkCyRmJQDMYXwDZOklI4ulIbKi9IMDrkpqToxBsZG5o5uJOwL0kg5LUihIQ7ZxfUFmUmZ5RouAIDKVUBc+8ZD0dBSMDIwMGBlCYQ1R/DgKHJaPYPoRY/hIGBotvDAzMExFiSVMYGLa3MTBI3EKIqcxjYOBvYWDYdqggsSgR7gDGbyzFacZGEDaPPQMD693//z9rMDCwT2Rg+Dvx///fi////7sYaP5tBoYDlQDwymImMx/pIAAAAGJlWElmTU0AKgAAAAgAAgESAAMAAAABAAEAAIdpAAQAAAABAAAAJgAAAAAAA5KGAAcAAAASAAAAUKACAAQAAAABAAAAXKADAAQAAAABAAAAXAAAAABBU0NJSQAAAFNjcmVlbnNob3Ti0gGEAAACPWlUWHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTpuczptZXRhLyIgeDp4bXB0az0iWE1QIENvcmUgNS40LjAiPgogICA8cmRmOlJERiB4bWxuczpyZGY9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkvMDIvMjItcmRmLXN5bnRheC1ucyMiPgogICAgICA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIgogICAgICAgICAgICB4bWxuczpleGlmPSJodHRwOi8vbnMuYWRvYmUuY29tL2V4aWYvMS4wLyIKICAgICAgICAgICAgeG1sbnM6dGlmZj0iaHR0cDovL25zLmFkb2JlLmNvbS90aWZmLzEuMC8iPgogICAgICAgICA8ZXhpZjpVc2VyQ29tbWVudD5TY3JlZW5zaG90PC9leGlmOlVzZXJDb21tZW50PgogICAgICAgICA8ZXhpZjpQaXhlbFhEaW1lbnNpb24+MTEwPC9leGlmOlBpeGVsWERpbWVuc2lvbj4KICAgICAgICAgPGV4aWY6UGl4ZWxZRGltZW5zaW9uPjEwMzwvZXhpZjpQaXhlbFlEaW1lbnNpb24+CiAgICAgICAgIDx0aWZmOk9yaWVudGF0aW9uPjE8L3RpZmY6T3JpZW50YXRpb24+CiAgICAgIDwvcmRmOkRlc2NyaXB0aW9uPgogICA8L3JkZjpSREY+CjwveDp4bXBtZXRhPgrwnq5tAAATB0lEQVR4Ae1cCWxc1RW943Vsj/exsxAnwWS1A4SlZStlh0JYRMvWllKCoK1KpYJUqoqqpUioUouqohYkKPsioGFpoUBa1oY1lBLWEJuQzdm87zNexjPuPW9yf56//5//58/iFM2V7P/+W+57c/799913333f19TUNEk5yhoCeVnrKdeRQiAHeJYFIQd4DvAsI5Dl7nISngM8ywhkubuchOcAzzICWe4uJ+FZBrwgy/3ZdhcrLaHQ8cdSrLSUxpYuJl94hIp27iJ/6+dU3LrZsl20upomaqopb3SUfGNj8evoGPkmJizrHwiZvple2k8Ea2ngvHModMJxtngUdPdQzf0PK/D1Sm333KHfGunCPe1U+t8N5P/0Myreus3IPxASMwp46IRjqe/Si1mqSxQWBT29lM/gQqrH5zdQpGEeTdTWqLI8lvj6W/+opF6AswNcynEF+P7PWqjsnXepaEebXjQj6RlTKQPnryL8gQB05bPPUdlb66eBMLp0CfVfdhGNM/i41t9627Q6iTIic2cT/oZOP5kCr79FgXVvzijw+XV1db9JNOBMlOlgl3z4MdXf9md+9bdbdlXQ00P5g4MU/urRBPVT/vKr5IvEdbQ8MMuGFpnjC+bT8Elfo2hVlXrI+YNDFrUym5V1KwUSK0CVvb2e6m6/k6AuEhEmUKHxhgZJer4Of/0E6vzptRQ+cqVnHl4bZh3wwfPPUWOFGql+/Amv4065XbS6krp/fA0NnnV6yrySYZARHT6y8jA16WEgmPQAblHbToqVlRIkHFRz30OOkq0qZvhf/8UX0kRdkGoeeTzDPcXZpxVwqIqh0081rA67XyD2tV15tvOHTz6R54khnrifz3jXaQEcFkTvVVcoS0JGLCae3GMxI2RljWBChBlY8sFHUi1r18L2DmW3Z6PDlAEH2J03XG9INSZCSAoWKzpBlXTecJ3KKmY7W6eRIw6nrmt/qLLm/uJX09rqddOdLujupdq772d7fa9iHZk9i9/SU9gSilD1X59Kd3eUEuBYsAjYeSO8MPn91IWJ3WihUnTCA8AbAX3fzcDPvvm3enHG0vkDgwrsoh07VR9RdhP0/OAqnn/mxfvMy6Pqx9I7sadkpfSsvsKQbLdgW6EHs1AsFrwxPau/Z/C1qp+OvLxQWIFdvGWrYhcLBKhbB5tzh047mQbPPC0d3Rk8PAMOFQFVAKp+/MkpS26Du5aIBuNLdC1rShK6u/zl11Qe/Cp4c2DtZIJ84+MUZDXib4mrtsniIgZ7NY0talTdYSziMOu/5JsUOubotA3Ds0qBHwQE9YDVnxPls64UgiqyWuxAyvPCYbUwgqR3/eRHSp9DXaWNYjEK/oXBZseWIp+Puq+5ikablqlb5NfdeQ9FywK09+ZfUqw8QL3fv5zy+wdo0XCY8ljNtO2MqyAvY/Is4XClgqwsDquBFGmDTLRaxIQLf4lIGKwXgJ8uCt79AMGdINR9zWp+kw5Vt/6WzQpsisaUOyF4zwMqf7KokAZZfdYtX04N8xpo3kEHSfOkr54Al8ULeiv50J0ZB4nGxAgSVaRuLP7BWziLPYOYPKGudIAsqrvOqr33ISp9732jfs/qy9lHc5S6L96yjYJ33UM+9qcL+Tduoqon/qZuR1kltq6IvwUL5i8g9kFJtaSungCHvSxkNv8k3+pa9tY7KlveDqs6ep6oq/KXnFWW3s4qXfPgo8pFK2V9373U8MEXte1isO+lvKFhKTaulS++QoH176n7luZltK6zndb/513q7e0lH6ujZMkT4OK/Npt3Tp3DRgehvTiwnNqko7z60TUUeOMtgxWW80OnfF3dF+7tUGDn9/YZ5XpicnKSyv/5IvnGI8QIUz9bLtFoVP2hLFnyBLh0onvxJA9X6Fx5KHo+3gaxRAB4OnWz3o+erlrzNJW/us7IGrhgleGwwqIHkl3Q0WmUWyUKd+2h8lfiFhRUkJNKtOIheSkBrqsWYYgrFi+7/vQHSynGRoPocph+mQS96ulnqYJVgtDg2Weq7TzcY9EDnV24a7cUG9eioiKaPWsWzZk92/hb9PFGKuI2oNFV3zDyUSfANrxb8gS4WBCQYrMkw3kFywIk9fTBYPIMwgfOph7aykpVr5OOdOU/1lLFC/8yWGER0/+tC9S9GgNLdtG2HUa5JAJsDh658gg6pPEQajy40fhbGqyn5tYvVLWhhfMp7/TTjLJDm1dQSUl8m1D42F092eG6iTdw3ioFHjrAqyYSC7BhbVgRdD9Wpp0/v56KP99saZNbtXObV7H2Jap85jmj+vCJJ1Dfty9W99gtghop/jwOnlGJEwCtuamJ8vPz9WwjvWRjK20/5GDqq62mvQ1zaSFbNiDY5o0LD6aNm/bZ9kaL6QlPgKtOWFIhoUNnnDqNKwCtu+POafl6hoCOLbR0UvlLr1HVU383WIaO/QovXL5j3ANsmHtm8hcXK9BGx0aJ9luG5mpUzRYNAN990BwaGgmTjxdSoILCAsLbMRyabunoTJIGHFKs+1DADOBhAo2w0yfGUoI/N4R26aTAv99gD9+TBktsofVcfaVxH7zrPlubfpTjWtxIaLiIITviUIr4i2l9vo9KtUWU0VGCRFKAYzkPsEHQwbCPYeqJLS4uWOjw9l/fqBxS6Vq0JPgNqqjszXem7NqMrGiiHl5FCtXyDpO+6JH8ZK/+TS1GE/h6St//wLh3k3ANOHSzgK3UAa8Ezf4Q6Oza+x9S9QA6fCGog4ci3kA3g0q2ThkvTGofeMRoNrZksQJ7kl9zUM3Dj/EY3jXKU0nAy4hV6Rjr8pHDViTNyhXg0NUw9UB2YEvP8K3AUSWxJGgrE6nUSdcVD9I3EaWahx41WI4fvICdUVeq/VNkwjWAWBQzYaKbz36RYr/fXOR4n9/VQ9sYcOzR1rO1Ar0uFGOdvmXrFsLVilwBrpt6bjZ/IenwgwDoMXbj5vHkkgmqve/hKWwjB82l7qtXU7S6SuVXPfWMsdDSKwLs5uVNVFFRoWe7Tsd6+ylunxD52acSDE31Zvb191F3d7clP1eAi+8DEpXMRIe6ydS3HKHLTOy8d/MEOTEr7lSqfPYFqlj74rTWAHvZkqWewQbDMs3nMs6+dDNVc6CRZ8BhlchCJhO72ngL0IdsMsN1K3Z+Ib+qpS68kdGqSqWzIw1xt6mywy124H3ko7pgHYV5wsefkI8T8IroVymzu/rYjzLJvpWu8XEq2bNnSrWJ6MSUe/3GUcJF/0JSxRrRGXhN462BP0Ueps5H3L+4Wtn5el2EN8P0G2tcqLLhq9HtcL0uQ0QdnR16lud0flc3TdTXUU9knKI7trvm4wi4/HirZbreCwAMK0ldohZEeECFHPwD60BfcQLgXt6zFL7gAd8KtrWw2wOrBhMtgIzPAfvDK/T+kJ4sKFBgjy5booowOWKSzAZB+AB4NFCWVHeOgAs3gGFFALDzZ9dNk1SAhT/sTwJMmIsTtVyXHVYAFISHCDWlPxBzH6g7cP65KnTBXNZzzZVsmjWrbDxYmH/ZogKWcFCsLEOA2/0QPGn4QwA8FjkIaYN0C9gIfYCO7gxerwAHgFg0YSGCB+FEkHjUQ6yImcJHHaGySt/boPiZy3E/d85c/ptjVZRS3qflFQRPUTn/7qOPjO8a6QzbO9pp1+7pnkjXEq4zM6exqMGqU7dIABKkF3pa930D7FRCKsx9475wb7tVttp7xHZYJmiUJ2qQnzcmitkPYya/39q94ck9a2YOKdTB1ssBur68D95+l21dvV2q6Vnsz84U2BhbKBBQQyxmH4wVFe5b5ZrLHCUcQMJkwyRXSckHO0LVSHyJk742D87rPSQuygerWj9v9crCsd1gSdy3PsQhclb9jHOonBW5ADwegyF2shWTRHlQJyDl7Hr51URV01Y2xlKHv0zRZGEhRTheBTTW1UXdSbiYHVWKPrFJ8I/VDxHLw1w2svJwlQUdD9XzZSA56IXfkjccSuonOUo4QMKSXi1UeHcHD8AMHGIBo6w6zAeeoIbkQYBHtgh7knkeQhjcjm+CT9gJ+Xmlic0LM0XZeRWxUCuOgIMRpBOAQx/3XXoR29T7nUYAW85Y4g3QI7FEDWEecFql4sHASYY25gdn/jFO903LllNZkvaxE0+9fMOx+2MNj6mspmILs3A3m4Tb23bozVTaFeAATEw8ARegw76We0iwDja4Y/sM7cxvxLRRcAZ8KKLvrcoPpLzOOfVqOLN3t1OxFqmljzEy4XHSFCYADhIOSQfI8SPa8SU1VoxYyJjJ/ADM5f+P9yFeyvdxHDlo/tbpEiy/adTmQbiScGEioAJ0SDcI1ofThrG0T3R1CmdO1NZc9ulnGz2FoZn5WN0P8XlRoY61a6mnr19up1wnbM77JwU4OAJ0xOL18algkNUkqgqS/IeHCHJykrlha/dj3bR1qhPmnR5QyUef0GRnF1krDnsujmahVdOyt98xsjGhuiH4VuwI1ox4DwMab7v6M5UPlRred0jAKtTCzbiSlnAwlfhuuFXtlvR657LbD4+hWa/jQej7peZynY/bdE0Nnw0t8PTTEnaxc9VZFKsoVyFv8/lcUGF9fPI0NwoND1PIxrvqaVRi7uHLD25o+PjjVDUVz1JSapyYgFQDbPEgYr80HYTN4XSbhb0s3e/vU3vLN2+lpvrZRNZ404YPP7D9GZ5UinBzI92oi0lV6kL349WEuxXHCAXsdHsQZYzpurY2L+UtNV6T8AHaxZs227INhUI0om3fmSt6knBhIqtIube7wg7Ht072/O4WFZWFICFpiwcRvOMu24URVI7sVdrxN+cjigqbxemijgUNtH1RfLJcyFG0EwMDZLdruWfvnoTdpgQ4dnDcEkDHBIvFjYCNxZKYmjofqJrQ8cew6bnSqKuXO6VbWvdHRznVdSqf5JC2jnPPVNUQ2tz/yGO0wcbkc+KFck+ASwBmdN/Xetx0hDoAWFaTmHCtwEa51HHLN5P1enCkncOTQeWvvZHy97Q8AY7wBRB0Mf6c/CSqMv/T6yEw30y6XwYPBG9EIaucSfazyNFwc5tM3sNvJN9UCXDsYmDdGyl35wlw6F0AAjclHE5u4wbF1sao5aHJL4BU636Z+JnNuDtXbyf1E10b5s0jeAxToX6OBG474xTFonLnbjry9beJGhttWQ6wXnfjF/cEOHrFiTQFEptKOBirS6/tqLQCsVqQFbdaTlWl2I6zUjVaU8dkbU1tSmZhlAPyX7v8UtUPnFNnv7SOfLPYDLQhOKq279hhUzo12/NUDpDhR8EEKAuXqazd32FZDz7gV3vfg+4bZqDmYGUFrbnyMoPzWc+sJURZJaKt27YRTra5Ic8SDquj8pnnlU8Fphv0L4Lh3bhizQODhIOwyvTS3syvt6+PV3rJ7cSARw9Hb3140XkGu6MeWUMhtkwScRriOEO7OEKDkZbwDDh4QMrxqQtx2UZ4JwSrRV1daH1NSeqTLVRIqmpEZ962s02/dZUePulE6r3kQlUXMeBzbrqFuvh8fZer1u4rpQQ4uhGgADokvf2mG1UkFbyIAB5HUWBlwGZHKJwQjhwmq/elbTqvkTn8QZrTTiF8hgmEOSR4570pm392Y0wZcDAG6AhX67uMv7LJ53tgVThZFgBf36C2G2Cm8vF9FHw8EmDHSuJB+eWvrOMP0qzJVJeKb1oAByfoXwAYYkcVIl71nW35BSLxcH7hjUCbRHGF0i7Z6+JFi6l8X6COVdsthzfTVj4uEqosV8VFbIk08pJ9GXwkfEYzEcUmY7SjrY36eJ7wQmkDHJ2r5Tvrdeh2WB3ixkUZYr5RjnzxqcQ/bTr9rBDqp0IIBDIfVO3lr0G08XGU3ewXGdwHNCLCl/B3aXH+Ek4pbpSw22gsSptaWgg2t1dKK+D6IACulfQiHyoIK0fofETTOk20+vabBOvrfSVKf7FsMW1jx1P3rLop1RZu2a6Aru2KR8FOKbS4GedwiM9aNhG8galQxgBPNCioHjntJhMtFlIIptctHLwNCCTCaWcQyvDArAjOrgife4f1s47jtiN8zmecbWqdCkZGqQIb3jwxVvIxbny9Jf4FF73W9DS27PoH+m0PSk1vYZ8zI4BjOGJzwzmEiRbLelnaA1hYNQBcpyqbYPuBfZ9X1etKGiZeyScbqeTjT5UFgu9dIQgu8fcjpHX6rzP6/XD8HICKgHtsw9mdYMYKFL4VPCSdOngDQ3afiFeDBfzNE3z3pIA/HoOrf1Or+na43mam0zMOuA4ATEkDQC6A+sA3DXU1o9dHGgdUFdBauAL2M718rQf88NEZnLG0O2eJOqnQAQV4Kj9Eb7uiuZkqKyr1LMc0zLzdvFuTigXi2AlXmDEd7mZw3uv4XDXFznpXVyf/dZFdPLcrRklU+pICPt27B0DD7NAKs5oKM9BDw0PqmgRWaan6pVQpaUEmQ0w8+8MzNJ4vPdsc4Fl+xDnAc4BnGYEsd5eT8BzgWUYgy93lJDwHeJYRyHJ3OQnPAZ5lBLLc3f8ALnCr7Vg8npQAAAAASUVORK5CYII=
    mediatype: image/png   
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - '*'
          resources:
          - '*'
          verbs:
          - '*'
        - nonResourceURLs:
          - '*'
          verbs:
          - '*'
        serviceAccountName: openaihub-operator
      deployments:
      - name: openaihub-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: openaihub-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: openaihub-operator
            spec:
              containers:
              - command:
                - kfctl
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: openaihub-operator
                image: aipipeline/openaihub-operator:v1.1.0
                imagePullPolicy: Always
                name: openaihub-operator
                resources: {}
              serviceAccountName: openaihub-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  maturity: alpha
  links:
  - name: Kubeflow
    url: https://www.kubeflow.org/
  provider:
    name: Kubeflow
  maintainers:
    - name: Animesh Singh
      email: singhan@us.ibm.com
    - name: Tommy Li
      email: tommy.chaoping.li@ibm.com
    - name: Weiqiang Zhuang
      email: wzhuang@us.ibm.com
    - name: Mofizur Rahman
      email: moficodes@ibm.com
  keywords: 
    - Kubeflow
    - Operator
    - OpenAIHub
    - IBMCloud
    - GCP
    - OpenShift
  version: 1.1.0
  selector:
    matchLabels:
      component: openaihub-operator
